"""Tests for tools/generate_architecture_snapshot.py — tier-1 snapshot generator.

Contract:
  - Running the generator produces CURRENT.generated.md under docs/architecture/.
  - Two runs on the same root produce byte-for-byte identical output.
  - Generated doc contains exactly 3 sections (Layer Map, NATS Subjects & Identities,
    Process Topology); Module/Symbol Inventory is absent.
  - Generated doc includes autogenerated header/footer.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path  # noqa: F401 — used in type annotations and tmp_path fixtures

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _setup_minimal_project(root: Path) -> None:
    """Create a minimal fake project structure so the generator can run."""
    # src/ with one valid module
    src = root / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "fake.py").write_text("class Fake:\n    ...\n", encoding="utf-8")

    # deploy/quadlet.toml
    deploy = root / "deploy"
    deploy.mkdir(parents=True, exist_ok=True)
    (deploy / "quadlet.toml").write_text(
        "[component.fake]\ncontainer = \"fake\"\n", encoding="utf-8"
    )

    # deploy/nats/acl-matrix.json
    nats = deploy / "nats"
    nats.mkdir(parents=True, exist_ok=True)
    (nats / "acl-matrix.json").write_text(
        '{"subjects": ["lyra.inbound"], "identities": {}}', encoding="utf-8"
    )

    # .importlinter
    (root / ".importlinter").write_text(
        "[importlinter:contract:1]\n"
        "name = test\n"
        "type = layers\n"
        "layers = src\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# tests
# ---------------------------------------------------------------------------


def test_generator_produces_file(tmp_path: Path):
    _setup_minimal_project(tmp_path)
    result = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert (tmp_path / "docs" / "architecture" / "CURRENT.generated.md").exists()


def test_determinism(tmp_path: Path):
    _setup_minimal_project(tmp_path)
    run1 = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert run1.returncode == 0
    path = tmp_path / "docs" / "architecture" / "CURRENT.generated.md"
    content1 = path.read_text()

    path.unlink()
    run2 = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert run2.returncode == 0
    content2 = path.read_text()

    assert content1 == content2


def test_missing_importlinter_exits_2(tmp_path: Path):
    _setup_minimal_project(tmp_path)
    (tmp_path / ".importlinter").unlink()
    result = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 2


def test_output_structure(tmp_path: Path):
    _setup_minimal_project(tmp_path)
    result = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0
    content = (tmp_path / "docs" / "architecture" / "CURRENT.generated.md").read_text()

    # Three kept sections must be present
    assert "## Layer Map" in content
    assert "## NATS Subjects & Identities" in content
    assert "## Process Topology" in content

    # Symbol inventory must be absent
    assert "## Module / Symbol Inventory" not in content

    # Autogenerated markers
    assert "AUTOGENERATED" in content
    assert "DO NOT EDIT BY HAND" in content
