"""Tests for tools/generate_architecture_snapshot.py — tier-1 snapshot generator.

Contract:
  - Running the generator produces CURRENT.generated.md under docs/architecture/.
  - Two runs on the same root produce byte-for-byte identical output.
  - Syntax errors in scanned source cause exit code 2.
  - Generated doc contains all 4 sections plus autogenerated header/footer.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest
from tools.code_inventory import CodeInventory
from tools.generate_architecture_snapshot import build_inventory

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------


def _setup_minimal_project(root: Path) -> None:
    """Create a minimal fake project structure so the generator can run."""
    # src/ with one valid module
    src = root / "src"
    src.mkdir(parents=True, exist_ok=True)
    (src / "fake.py").write_text("class Fake:\n    ...\n", encoding="utf-8")

    # deploy/quadlet.toml
    deploy = root / "deploy"
    deploy.mkdir(parents=True, exist_ok=True)
    (deploy / "quadlet.toml").write_text(
        "[component.fake]\ncontainer = \"fake\"\n", encoding="utf-8"
    )

    # deploy/nats/acl-matrix.json
    nats = deploy / "nats"
    nats.mkdir(parents=True, exist_ok=True)
    (nats / "acl-matrix.json").write_text(
        '{"subjects": ["lyra.inbound"], "identities": {}}', encoding="utf-8"
    )

    # .importlinter
    (root / ".importlinter").write_text(
        "[importlinter:contract:1]\n"
        "name = test\n"
        "type = layers\n"
        "layers = src\n",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# tests
# ---------------------------------------------------------------------------


def test_generator_produces_file(tmp_path: Path):
    _setup_minimal_project(tmp_path)
    result = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    assert (tmp_path / "docs" / "architecture" / "CURRENT.generated.md").exists()


def test_determinism(tmp_path: Path):
    _setup_minimal_project(tmp_path)
    run1 = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert run1.returncode == 0
    path = tmp_path / "docs" / "architecture" / "CURRENT.generated.md"
    content1 = path.read_text()

    path.unlink()
    run2 = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert run2.returncode == 0
    content2 = path.read_text()

    assert content1 == content2


def test_error_handling_syntax_errors(monkeypatch, tmp_path: Path):
    def mock_build(root):
        return CodeInventory(
            root=root,
            modules=set(),
            symbols={},
            subjects=frozenset(),
            builtin_names=frozenset(),
            syntax_errors=[(Path("fake.py"), "syntax error")],
        )

    monkeypatch.setattr(
        "tools.generate_architecture_snapshot.CodeInventory.build", mock_build
    )

    with pytest.raises(SystemExit) as exc_info:
        build_inventory(tmp_path)
    assert exc_info.value.code == 2


def test_output_structure(tmp_path: Path):
    _setup_minimal_project(tmp_path)
    result = subprocess.run(
        [sys.executable, "tools/generate_architecture_snapshot.py", str(tmp_path)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0
    content = (tmp_path / "docs" / "architecture" / "CURRENT.generated.md").read_text()
    assert "## Layer Map" in content
    assert "## Module / Symbol Inventory" in content
    assert "## NATS Subjects & Identities" in content
    assert "## Process Topology" in content
    assert "AUTOGENERATED" in content
    assert "DO NOT EDIT BY HAND" in content
