#!/usr/bin/env bash
# Generate nkey seeds for NATS authentication
#
# Seeds (private keys) → ~/.lyra/nkeys/     owned by LYRA_USER, 0600 — no system access needed
# auth.conf (public keys) → /etc/nats/nkeys/ owned by root:nats,  0640 — read by nats-server
#
# Creates 7 user nkey seeds: hub, telegram-adapter, discord-adapter,
#                             tts-adapter, stt-adapter, llm-worker, monitor
#
# Usage: sudo ./deploy/nats/gen-nkeys.sh
#        sudo ./deploy/nats/gen-nkeys.sh --fix-perms      # re-apply permissions without regenerating
#        sudo ./deploy/nats/gen-nkeys.sh --show           # print existing public keys
#        sudo ./deploy/nats/gen-nkeys.sh --regenerate     # atomic backup + wipe + regenerate
#        sudo ./deploy/nats/gen-nkeys.sh --regenerate --yes  # non-interactive regenerate
#             ./deploy/nats/gen-nkeys.sh --template-only  # write auth.conf skeleton to stdout (no root needed)
#
# Idempotent — skips if auth.conf already exists. Delete auth.conf + seeds dir to regenerate.
# Override seeds location: SEEDS_DIR=/custom/path sudo ./gen-nkeys.sh

set -euo pipefail

LYRA_USER="${SUDO_USER:-$(id -un)}"
LYRA_HOME=$(getent passwd "$LYRA_USER" | cut -d: -f6)
SEEDS_DIR="${SEEDS_DIR:-${LYRA_HOME}/.lyra/nkeys}"
AUTH_DIR="/etc/nats/nkeys"
AUTH_CONF="${AUTH_DIR}/auth.conf"
NK_BIN=""

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[+]${NC} $1" >&2; }
warn()  { echo -e "${YELLOW}[!]${NC} $1" >&2; }
error() { echo -e "${RED}[x]${NC} $1" >&2; exit 1; }

# ── ACL matrix (T1.2) ─────────────────────────────────────────────────────────
# Source of truth: artifacts/specs/706-per-role-nkeys-acls-spec.mdx §Data Model
# If spec matrix changes, update these arrays — they are the executable copy.
declare -A PUB_ALLOW SUB_ALLOW

PUB_ALLOW[hub]='"lyra.outbound.telegram.>","lyra.outbound.discord.>","lyra.voice.tts.request","lyra.voice.stt.request","lyra.llm.request"'
SUB_ALLOW[hub]='"lyra.inbound.telegram.>","lyra.inbound.discord.>","lyra.voice.tts.heartbeat","lyra.voice.stt.heartbeat","lyra.llm.health.*","lyra.system.ready","_INBOX.>"'

PUB_ALLOW[telegram-adapter]='"lyra.inbound.telegram.>","lyra.system.ready"'
SUB_ALLOW[telegram-adapter]='"lyra.outbound.telegram.>"'

PUB_ALLOW[discord-adapter]='"lyra.inbound.discord.>","lyra.system.ready"'
SUB_ALLOW[discord-adapter]='"lyra.outbound.discord.>"'

PUB_ALLOW[tts-adapter]='"lyra.voice.tts.heartbeat"'
SUB_ALLOW[tts-adapter]='"lyra.voice.tts.request"'

PUB_ALLOW[stt-adapter]='"lyra.voice.stt.heartbeat"'
SUB_ALLOW[stt-adapter]='"lyra.voice.stt.request"'

PUB_ALLOW[llm-worker]='"lyra.llm.health.*"'
SUB_ALLOW[llm-worker]='"lyra.llm.request"'

PUB_ALLOW[monitor]='"lyra.monitor.>"'
SUB_ALLOW[monitor]='"lyra.monitor.>"'

IDENTITIES=(hub telegram-adapter discord-adapter tts-adapter stt-adapter llm-worker monitor)

# ── emit_user (T1.3) ──────────────────────────────────────────────────────────
# Writes one authorization users[] entry block to stdout.
# Args: name pubkey
emit_user() {
  local name="$1" pubkey="$2"
  cat <<USER
    {
      nkey: "${pubkey}"
      # ${name}
      permissions: {
        publish:   { allow: [${PUB_ALLOW[$name]:-}] }
        subscribe: { allow: [${SUB_ALLOW[$name]:-}] }
        allow_responses: true
      }
    }
USER
}

# ── flag parsing ───────────────────────────────────────────────────────────────
SHOW_ONLY=false
FIX_PERMS=false
TEMPLATE_ONLY=false
REGENERATE=false
AUTO_YES=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --show)          SHOW_ONLY=true;    shift ;;
    --fix-perms)     FIX_PERMS=true;    shift ;;
    --template-only) TEMPLATE_ONLY=true; shift ;;
    --regenerate)    REGENERATE=true;   shift ;;
    --yes)           AUTO_YES=true;     shift ;;
    *) error "Unknown option: $1" ;;
  esac
done

# ── template-only mode (T1.4) — no root, no filesystem writes ─────────────────
if [ "${TEMPLATE_ONLY}" = true ]; then
  echo "# NATS nkey authorization — generated by gen-nkeys.sh --template-only"
  echo "# Spec: artifacts/specs/706-per-role-nkeys-acls-spec.mdx"
  echo "# ACL for roxabi-nats SDK identities intentionally omitted — deferred until ADR-045 lands."
  echo "# DO NOT use these dummy pubkeys in production."
  echo "# Regenerate with: sudo ./deploy/nats/gen-nkeys.sh --regenerate"
  echo "authorization {"
  echo "  users: ["
  for name in "${IDENTITIES[@]}"; do
    # Produce a stable dummy pubkey per identity (uppercase name, no hyphens)
    local_dummy="UDUMMY${name//-/}"
    emit_user "$name" "${local_dummy^^}"
  done
  echo "  ]"
  echo "}"
  exit 0
fi

# ── root check (required for all other modes) ──────────────────────────────────
[ "$(id -u)" -eq 0 ] || error "Must be run as root (sudo ./deploy/nats/gen-nkeys.sh)"

# ── show mode ──────────────────────────────────────────────────────────────────
if [ "${SHOW_ONLY}" = true ]; then
  [ -f "${AUTH_CONF}" ] || error "auth.conf not found at ${AUTH_CONF} — run without --show first"
  echo "Public keys (${AUTH_CONF}):"
  grep -E 'nkey:|# ' "${AUTH_CONF}"
  echo ""
  echo "Seed files (${SEEDS_DIR}):"
  if [ -d "${SEEDS_DIR}" ]; then
    ls -la "${SEEDS_DIR}/"*.seed 2>/dev/null || echo "  (no .seed files found)"
  else
    echo "  (directory not found)"
  fi
  exit 0
fi

# ── apply permissions ──────────────────────────────────────────────────────────
apply_permissions() {
  # Seeds — user-space, owned by LYRA_USER
  mkdir -p "${SEEDS_DIR}"
  chown "${LYRA_USER}:${LYRA_USER}" "${SEEDS_DIR}"
  chmod 0700 "${SEEDS_DIR}"
  # T1.5: extended to all 7 identities
  for seed in hub telegram-adapter discord-adapter tts-adapter stt-adapter llm-worker monitor; do
    if [ -f "${SEEDS_DIR}/${seed}.seed" ]; then
      chown "${LYRA_USER}:${LYRA_USER}" "${SEEDS_DIR}/${seed}.seed"
      chmod 0600 "${SEEDS_DIR}/${seed}.seed"
    fi
  done
  # auth.conf — system, readable by nats-server (nats user)
  if [ -f "${AUTH_CONF}" ]; then
    chown root:nats "${AUTH_CONF}"
    chmod 0640 "${AUTH_CONF}"
  fi
  info "Permissions applied for LYRA_USER=${LYRA_USER}, SEEDS_DIR=${SEEDS_DIR}"
}

# ── fix-perms mode ─────────────────────────────────────────────────────────────
if [ "${FIX_PERMS}" = true ]; then
  [ -d "${SEEDS_DIR}" ] || error "${SEEDS_DIR} does not exist — run without --fix-perms first"
  apply_permissions
  exit 0
fi

# ── regenerate mode: atomic backup + wipe (T1.7) ──────────────────────────────
if [ "${REGENERATE}" = true ]; then
  if [ "${AUTO_YES}" = false ]; then
    if [ -t 0 ]; then
      read -r -p "This will wipe ~/.lyra/nkeys/ and /etc/nats/nkeys/auth.conf (backups will be created). Continue? [y/N] " reply
      [[ "${reply}" =~ ^[Yy]$ ]] || { warn "Aborted."; exit 0; }
    else
      error "stdin is not a TTY — pass --yes to confirm non-interactive wipe"
    fi
  fi

  epoch=$(date +%s)

  # Atomic backup: both must succeed before any delete
  if [ -f "${AUTH_CONF}" ]; then
    cp -a "${AUTH_CONF}" "${AUTH_CONF}.bak.${epoch}" \
      || error "Failed to back up ${AUTH_CONF} — aborting before any delete"
    info "Backed up auth.conf → ${AUTH_CONF}.bak.${epoch}"
  fi
  if [ -d "${SEEDS_DIR}" ]; then
    cp -a "${SEEDS_DIR}" "${SEEDS_DIR}.bak.${epoch}" \
      || error "Failed to back up ${SEEDS_DIR} — aborting before any delete"
    info "Backed up seeds → ${SEEDS_DIR}.bak.${epoch}/"
  fi

  # Only delete after both backups succeeded
  rm -f "${AUTH_CONF}"
  rm -rf "${SEEDS_DIR}"
  info "Old keys wiped. Regenerating..."
fi

# ── idempotency check ──────────────────────────────────────────────────────────
if [ -f "${AUTH_CONF}" ]; then
  warn "auth.conf already exists — skipping. Remove ${AUTH_CONF} + ${SEEDS_DIR}/ to regenerate."
  warn "To re-apply permissions only: sudo ./deploy/nats/gen-nkeys.sh --fix-perms"
  warn "To atomically back up and regenerate: sudo ./deploy/nats/gen-nkeys.sh --regenerate"
  exit 0
fi

# ── locate or download nk ─────────────────────────────────────────────────────

ensure_nk() {
  if command -v nk &>/dev/null; then
    echo "nk"; return
  fi

  info "nk not found — downloading from GitHub releases..."

  local arch
  arch=$(dpkg --print-architecture 2>/dev/null \
    || uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/')

  local tmpdir
  tmpdir=$(mktemp -d)
  trap 'rm -rf "${tmpdir}"' EXIT

  # Resolve download URL directly from GitHub API assets (avoids guessing filename pattern)
  local release_json url version
  release_json=$(curl -fsSL --connect-timeout 10 \
    "https://api.github.com/repos/nats-io/nkeys/releases/latest" 2>/dev/null) || release_json=""

  if [ -n "${release_json}" ]; then
    url=$(echo "${release_json}" | python3 -c "
import sys, json
data = json.load(sys.stdin)
arch = '${arch}'
for asset in data.get('assets', []):
    n = asset['name'].lower()
    if 'nk' in n and 'linux' in n and arch in n and n.endswith('.zip'):
        print(asset['browser_download_url'])
        break
" 2>/dev/null) || url=""
    version=$(echo "${release_json}" | python3 -c "
import sys, json; print(json.load(sys.stdin).get('tag_name','v0.4.6').lstrip('v'))
" 2>/dev/null) || version="0.4.6"
  fi

  # Fall back to known-good release if API didn't yield an asset URL
  if [ -z "${url}" ]; then
    version="0.4.6"
    url="https://github.com/nats-io/nkeys/releases/download/v${version}/nk-v${version}-linux-${arch}.zip"
    warn "Could not resolve asset URL from API — falling back to v${version}"
  fi

  info "Downloading nk v${version}..."
  curl -fsSL "${url}" -o "${tmpdir}/nk.zip" \
    || error "Failed to download nk v${version} from ${url}"

  if command -v unzip &>/dev/null; then
    unzip -q "${tmpdir}/nk.zip" -d "${tmpdir}"
  else
    python3 -c "import zipfile,sys; zipfile.ZipFile(sys.argv[1]).extractall(sys.argv[2])" \
      "${tmpdir}/nk.zip" "${tmpdir}" \
      || error "Failed to extract nk.zip (no unzip and python3 extraction failed)"
  fi

  # Binary may be at root or inside a subdirectory
  local nk_bin
  nk_bin=$(find "${tmpdir}" -maxdepth 2 -name "nk" -type f | head -1)
  [ -n "${nk_bin}" ] || error "nk binary not found inside downloaded archive"
  chmod +x "${nk_bin}"

  # Verify SHA-256 when checksum file is available
  local sha_url
  sha_url="$(dirname "${url}")/SHA256SUMS"
  if curl -fsSL --connect-timeout 5 "${sha_url}" -o "${tmpdir}/SHA256SUMS" 2>/dev/null; then
    (cd "$(dirname "${nk_bin}")" \
      && grep -F "$(basename "${url}")" "${tmpdir}/SHA256SUMS" | sha256sum --check) \
      || error "SHA-256 check failed for ${url} — aborting before installing nk binary"
  else
    warn "SHA256SUMS not available for this release — skipping integrity check"
  fi

  cp "${nk_bin}" /usr/local/bin/nk
  info "nk v${version} installed to /usr/local/bin/nk"
  echo "/usr/local/bin/nk"
}

NK_BIN=$(ensure_nk)

# ── create directories ────────────────────────────────────────────────────────
apply_permissions   # creates SEEDS_DIR with correct ownership before writing seeds
mkdir -p "${AUTH_DIR}"
chown root:nats "${AUTH_DIR}"
chmod 750 "${AUTH_DIR}"

# ── generate nkey pairs (T1.5: extended to 7) ─────────────────────────────────

generate_nkey() {
  local name="$1"
  local seed_file="${SEEDS_DIR}/${name}.seed"
  local tmp_seed
  tmp_seed=$(mktemp)
  trap 'rm -f "${tmp_seed}"' RETURN

  "${NK_BIN}" -gen user > "${tmp_seed}"
  local pubkey
  pubkey=$("${NK_BIN}" -inkey "${tmp_seed}" -pubout) \
    || error "Failed to derive public key for ${name} — is the nk binary valid?"

  install -m 0600 -o "${LYRA_USER}" -g "${LYRA_USER}" "${tmp_seed}" "${seed_file}"
  echo "${pubkey}"
}

info "Generating nkey pairs in ${SEEDS_DIR}/ ..."
HUB_PUB=$(generate_nkey "hub")
TELEGRAM_PUB=$(generate_nkey "telegram-adapter")
DISCORD_PUB=$(generate_nkey "discord-adapter")
TTS_PUB=$(generate_nkey "tts-adapter")
STT_PUB=$(generate_nkey "stt-adapter")
WORKER_PUB=$(generate_nkey "llm-worker")
MONITOR_PUB=$(generate_nkey "monitor")

# ── write auth.conf via emit_user loop (T1.6) ─────────────────────────────────
# T1.7 (N7): header references spec + ADR-045 deferred note
{
  echo "# NATS nkey authorization — generated by gen-nkeys.sh"
  echo "# Spec: artifacts/specs/706-per-role-nkeys-acls-spec.mdx"
  echo "# ACL for roxabi-nats SDK identities intentionally omitted — deferred until ADR-045 lands."
  echo "# DO NOT edit manually — regenerate with: sudo ./deploy/nats/gen-nkeys.sh --regenerate"
  echo "# Seeds (private keys) live in: ${SEEDS_DIR}/"
  echo "authorization {"
  echo "  users: ["
  declare -A PUBKEYS=(
    [hub]="${HUB_PUB}"
    [telegram-adapter]="${TELEGRAM_PUB}"
    [discord-adapter]="${DISCORD_PUB}"
    [tts-adapter]="${TTS_PUB}"
    [stt-adapter]="${STT_PUB}"
    [llm-worker]="${WORKER_PUB}"
    [monitor]="${MONITOR_PUB}"
  )
  for name in "${IDENTITIES[@]}"; do
    emit_user "$name" "${PUBKEYS[$name]}"
  done
  echo "  ]"
  echo "}"
} > "${AUTH_CONF}"

chown root:nats "${AUTH_CONF}"
chmod 0640 "${AUTH_CONF}"

info "Done."
info "  Seeds:     ${SEEDS_DIR}/"
info "  auth.conf: ${AUTH_CONF}"
info ""
info "  hub.seed               NATS_NKEY_SEED_PATH=${SEEDS_DIR}/hub.seed"
info "  telegram-adapter.seed  NATS_NKEY_SEED_PATH=${SEEDS_DIR}/telegram-adapter.seed"
info "  discord-adapter.seed   NATS_NKEY_SEED_PATH=${SEEDS_DIR}/discord-adapter.seed"
info "  tts-adapter.seed       NATS_NKEY_SEED_PATH=${SEEDS_DIR}/tts-adapter.seed"
info "  stt-adapter.seed       NATS_NKEY_SEED_PATH=${SEEDS_DIR}/stt-adapter.seed"
info "  llm-worker.seed        NATS_NKEY_SEED_PATH=${SEEDS_DIR}/llm-worker.seed"
info "  monitor.seed           NATS_NKEY_SEED_PATH=${SEEDS_DIR}/monitor.seed"
warn "Supervisor confs already reference ~/.lyra/nkeys/ — no changes needed."
