#!/usr/bin/env bash
# deploy/install.sh — idempotent Quadlet install for factory
#
# Absorbs: make quadlet-install + make quadlet-secrets-install
# Does NOT restart services — defer to operator.
#
# Usage:
#   ./deploy/install.sh              # install units + secrets (skip if already present)
#   ./deploy/install.sh --dry-run    # print actions without executing
#   ./deploy/install.sh --secrets-only  # only (re)create Podman secrets
#   ./deploy/install.sh --force      # force --replace on secrets even if present
#
# Hard constraints (S5, grandfathered):
#   nkey seeds: ~/.roxabi/factory/nkeys/
#   env files:  ~/.roxabi/factory/env/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
QUADLET_SRC="${SCRIPT_DIR}/quadlet"
QUADLET_DST="${HOME}/.config/containers/systemd"
NKEYS_DIR="${HOME}/.roxabi/factory/nkeys"

DRY_RUN=0
SECRETS_ONLY=0
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --dry-run)       DRY_RUN=1 ;;
    --secrets-only)  SECRETS_ONLY=1 ;;
    --force)         FORCE=1 ;;
    *)               echo "Unknown argument: $arg" >&2; exit 1 ;;
  esac
done

run() {
  if [[ "$DRY_RUN" -eq 1 ]]; then
    echo "[dry-run] $*"
  else
    "$@"
  fi
}

log() { echo "==> $*"; }
warn() { echo "WARN: $*" >&2; }

# ── 1. Verify nkeys dir ──────────────────────────────────────────────────────

log "Checking ~/.roxabi/factory/nkeys/ ..."
if [[ ! -d "${NKEYS_DIR}" ]]; then
  echo "ERROR: ${NKEYS_DIR} not found. Run: make nats-setup" >&2
  exit 1
fi

# Refuse to install with placeholder nkeys still in the live auth.conf.
# Skipped under --dry-run so the operator can still preview install actions.
if [[ "$DRY_RUN" -eq 0 ]] \
  && [[ -f "${NKEYS_DIR}/auth.conf" ]] \
  && grep -qE '^[[:space:]]*nkey:[[:space:]]+"UDET' "${NKEYS_DIR}/auth.conf"; then
  echo "ERROR: ${NKEYS_DIR}/auth.conf still contains UDET* placeholder pubkeys." >&2
  echo "       Run: make nats-regen-authconf  (renders nkeys from ${NKEYS_DIR}/*.seed)" >&2
  exit 1
fi

# Parse the committed secrets manifest (generated by tools/emit_secrets_manifest.py).
# Defines: SECRET_SOURCES (name → relative path under ~/.roxabi/factory/, or 'n/a')
#          SECRET_POLICY  (name → nats-seed | nats-auth | generated | optional)
# NO runtime Python dependency — pure bash.
#
# STRICT PARSER: replaces the former `source` call to eliminate arbitrary-exec surface.
# Only accepts comment lines, blank lines, known block headers, block-close `)`
# and data lines matching ^[[:space:]]*\[([A-Za-z0-9_-]+)\]="([A-Za-z0-9._/-]*)"[[:space:]]*$.
# Any other line causes exit 2 — reject rather than execute.
_parse_secrets_manifest() {
  local file="$1"
  declare -gA SECRET_SOURCES=()
  declare -gA SECRET_POLICY=()
  local current=""
  local lineno=0
  # The `|| [[ -n "$line" ]]` clause ensures a final data line without a trailing
  # newline is still processed (read returns non-zero at EOF but may have read data).
  while IFS= read -r line || [[ -n "$line" ]]; do
    lineno=$(( lineno + 1 ))
    # Skip comment lines
    if [[ "$line" =~ ^[[:space:]]*# ]]; then
      continue
    fi
    # Skip blank / whitespace-only lines
    if [[ "$line" =~ ^[[:space:]]*$ ]]; then
      continue
    fi
    # Known block headers — exact string match is intentional fail-closed behaviour.
    # This parser requires the exact header strings emitted by tools/emit_secrets_manifest.py.
    # Any drift in the generator's formatting (leading whitespace, quoting, etc.) is
    # rejected with exit 2 by design — keep emit_secrets_manifest.py and this parser
    # in lockstep; ¬loosen to a regex.
    if [[ "$line" == 'declare -A SECRET_SOURCES=(' ]]; then
      current="SECRET_SOURCES"
      continue
    fi
    if [[ "$line" == 'declare -A SECRET_POLICY=(' ]]; then
      current="SECRET_POLICY"
      continue
    fi
    # Block close
    if [[ "$line" =~ ^[[:space:]]*\)[[:space:]]*$ ]]; then
      current=""
      continue
    fi
    # Data line: [KEY]="VALUE"
    if [[ "$line" =~ ^[[:space:]]*\[([A-Za-z0-9_-]+)\]=\"([A-Za-z0-9._/-]*)\"[[:space:]]*$ ]]; then
      if [[ -z "$current" ]]; then
        echo "ERROR: secrets-manifest.sh: refusing to parse unexpected line ${lineno}: ${line}" >&2
        exit 2
      fi
      local _key="${BASH_REMATCH[1]}"
      local _val="${BASH_REMATCH[2]}"
      # Reject values containing a '..' segment — defense-in-depth against a tampered
      # manifest pointing `podman secret create` at an arbitrary operator-readable file
      # via path traversal.  No legitimate secret source path or policy word contains '..'.
      if [[ "$_val" == *..* ]]; then
        echo "ERROR: secrets-manifest.sh: refusing manifest value with '..' path segment on line ${lineno}: ${line}" >&2
        exit 2
      fi
      if [[ "$current" == "SECRET_SOURCES" ]]; then
        SECRET_SOURCES["${_key}"]="${_val}"
      else
        SECRET_POLICY["${_key}"]="${_val}"
      fi
      continue
    fi
    # Anything else is rejected
    echo "ERROR: secrets-manifest.sh: refusing to parse unexpected line ${lineno}: ${line}" >&2
    exit 2
  done < "$file"
}

if [[ ! -f "${SCRIPT_DIR}/generated/secrets-manifest.sh" ]]; then
  echo "ERROR: ${SCRIPT_DIR}/generated/secrets-manifest.sh not found." >&2
  echo "       run: python3 tools/emit_secrets_manifest.py" >&2
  exit 2
fi
_parse_secrets_manifest "${SCRIPT_DIR}/generated/secrets-manifest.sh"

# Resolve SECRET_SOURCES relative paths to absolute host paths.
# 'n/a' entries are handled per-policy below (generated/optional — no source file).
FACTORY_DATA_DIR="${HOME}/.roxabi/factory"
declare -A SEEDS=()
for _secret_name in "${!SECRET_SOURCES[@]}"; do
  _rel="${SECRET_SOURCES[$_secret_name]}"
  if [[ "${_rel}" != "n/a" ]]; then
    SEEDS["${_secret_name}"]="${FACTORY_DATA_DIR}/${_rel}"
  fi
done
unset _secret_name _rel

# ── 2. Generate blobstore bearer token (idempotent) ────────────────────────

BLOBSTORE_TOK="${HOME}/.roxabi/factory/blobstore.tok"
if [[ ! -f "${BLOBSTORE_TOK}" || "$FORCE" -eq 1 ]]; then
  log "Generating blobstore bearer token → ${BLOBSTORE_TOK} ..."
  run mkdir -p "${HOME}/.roxabi/factory"
  if [[ "$DRY_RUN" -eq 0 ]]; then
    (umask 0077; openssl rand -base64 48 > "${BLOBSTORE_TOK}")
  else
    echo "[dry-run] would generate ${BLOBSTORE_TOK} (64 base64 chars, mode 0600)"
  fi
else
  echo "  [skip] ${BLOBSTORE_TOK} already exists (use --force to regenerate)"
fi
# Wire generated token path into SEEDS so the policy loop can install it.
SEEDS[factory_blobstore_token]="${BLOBSTORE_TOK}"

# ── 3. Bootstrap blobstore.env (idempotent) ─────────────────────────────────

ENV_FILE="${HOME}/.roxabi/factory/env/blobstore.env"
if [[ ! -f "${ENV_FILE}" || "$FORCE" -eq 1 ]]; then
  log "Generating ${ENV_FILE} ..."
  run mkdir -p "$(dirname "${ENV_FILE}")"
  if [[ "$DRY_RUN" -eq 0 ]]; then
    TS_IP=$(tailscale ip -4 2>/dev/null | head -1 || true)
    # `run` only wraps exec; stream redirection (>) is dry-run-gated via the if block above.
    (umask 0077; printf 'TAILSCALE_IPV4=%s\n' "${TS_IP}" > "${ENV_FILE}")
    log "[ok] generated ${ENV_FILE} (TAILSCALE_IPV4=${TS_IP:-<empty>})"
  else
    echo "[dry-run] would generate ${ENV_FILE} (TAILSCALE_IPV4 from tailscale ip -4)"
  fi
else
  echo "  [skip] ${ENV_FILE} already exists (use --force to regenerate)"
fi

# Validate that all required (non-optional) seed files are present before touching podman.
MISSING=0
for secret_name in "${!SEEDS[@]}"; do
  _policy="${SECRET_POLICY[$secret_name]:-}"
  # optional policy: skip-if-absent is expected — not an error at this validation stage.
  if [[ "${_policy}" == "optional" ]]; then
    continue
  fi
  # generated policy: install.sh creates the file itself in step 2. In a live run it
  # already exists by now; in --dry-run generation is simulated, so its absence here is
  # expected, not a failure.
  if [[ "${_policy}" == "generated" && "$DRY_RUN" -eq 1 ]]; then
    continue
  fi
  seed_path="${SEEDS[$secret_name]}"
  if [[ ! -f "${seed_path}" ]]; then
    warn "Missing seed file: ${seed_path} (needed for secret ${secret_name})"
    MISSING=1
  fi
done
unset _policy
if [[ "$MISSING" -eq 1 ]]; then
  echo "ERROR: Missing seed files — cannot install secrets. Run: make nats-setup" >&2
  exit 1
fi

# ── 4. Install Podman secrets ────────────────────────────────────────────────
# Policy dispatch:
#   nats-seed  → podman secret create from seed file
#   nats-auth  → podman secret create from auth.conf file
#   generated  → podman secret create from locally generated token file
#   optional   → skip-if-absent (warn, no error)

log "Installing Podman secrets ..."
for secret_name in "${!SECRET_POLICY[@]}"; do
  _policy="${SECRET_POLICY[$secret_name]}"
  case "${_policy}" in
    nats-seed|nats-auth|generated)
      seed_path="${SEEDS[$secret_name]:-}"
      if [[ -z "${seed_path}" ]]; then
        warn "No source path resolved for ${secret_name} (policy=${_policy}) — skipping"
        continue
      fi
      already_exists=$(podman secret ls --format '{{.Name}}' 2>/dev/null | grep -Fx "${secret_name}" || true)
      if [[ -n "${already_exists}" && "$FORCE" -eq 0 ]]; then
        echo "  [skip] ${secret_name} already exists (use --force to replace)"
      else
        run podman secret create --replace "${secret_name}" "${seed_path}"
        echo "  [ok]   ${secret_name}"
      fi
      ;;
    optional)
      # Resolve source path uniformly via SECRET_SOURCES (policy always has a concrete source).
      _rel="${SECRET_SOURCES[${secret_name}]:-n/a}"
      if [[ "${_rel}" == "n/a" ]]; then
        warn "optional secret ${secret_name}: no source path in secrets-policy.toml — skipping"
        continue
      fi
      _src="${FACTORY_DATA_DIR}/${_rel}"
      if [[ ! -f "${_src}" ]]; then
        warn "${_src} not found — ${secret_name} secret not created"
        continue
      fi
      already_exists=$(podman secret ls --format '{{.Name}}' 2>/dev/null | grep -Fx "${secret_name}" || true)
      if [[ -n "${already_exists}" && "$FORCE" -eq 0 ]]; then
        echo "  [skip] ${secret_name} already exists (use --force to replace)"
      else
        # factory-claude-oauth requires stripping trailing newline.
        if [[ "${secret_name}" == "factory-claude-oauth" ]]; then
          run bash -c "tr -d '\\n' < '${_src}' | podman secret create --replace '${secret_name}' -"
        else
          run podman secret create --replace "${secret_name}" "${_src}"
        fi
        echo "  [ok]   ${secret_name}"
      fi
      ;;
    *)
      warn "Unknown policy '${_policy}' for ${secret_name} — skipping"
      ;;
  esac
done
unset _policy _rel _src

if [[ "$SECRETS_ONLY" -eq 1 ]]; then
  log "Done (--secrets-only)."
  exit 0
fi

# ── 5. Ensure data directories ──────────────────────────────────────────────

log "Ensuring data directories ..."
run mkdir -p "${HOME}/.roxabi/factory/blobstore"
echo "  [ok]   ${HOME}/.roxabi/factory/blobstore"
run mkdir -p "${HOME}/.roxabi/factory/turn-writer"
echo "  [ok]   ${HOME}/.roxabi/factory/turn-writer/"
# Pre-create turns.db as a regular file so Podman never materialises it as a
# directory on first boot (both factory-turn-writer and factory-hub bind-mount it;
# findings #1 + #2 — IsADirectoryError risk at SQLite open time).
if [[ ! -e "${HOME}/.roxabi/factory/turn-writer/turns.db" ]]; then
  run touch "${HOME}/.roxabi/factory/turn-writer/turns.db"
  echo "  [ok]   ${HOME}/.roxabi/factory/turn-writer/turns.db (pre-created)"
else
  echo "  [skip] ${HOME}/.roxabi/factory/turn-writer/turns.db already exists"
fi
# Pre-render auth.conf as a regular file so Podman never materialises it as a
# directory on first boot (factory-nats bind-mounts it inline; if the host file
# is absent, Podman creates a directory at the mount target, breaking nats-server).
if [[ ! -e "${NKEYS_DIR}/auth.conf" ]]; then
  run mkdir -p "${NKEYS_DIR}"
  log "Rendering auth.conf (first boot) → ${NKEYS_DIR}/auth.conf ..."
  run factory-acl genkeys --emit-merged-authconf
  echo "  [ok]   ${NKEYS_DIR}/auth.conf (rendered)"
else
  echo "  [skip] ${NKEYS_DIR}/auth.conf already exists"
fi

# ── 6. Copy Quadlet units ────────────────────────────────────────────────────

log "Copying Quadlet units to ${QUADLET_DST} ..."
run mkdir -p "${QUADLET_DST}"
for f in "${QUADLET_SRC}"/*.container "${QUADLET_SRC}"/*.network "${QUADLET_SRC}"/*.volume "${QUADLET_SRC}"/*.pod; do
  [[ -e "$f" ]] || continue
  run cp "$f" "${QUADLET_DST}/"
  echo "  [cp]   $(basename "$f")"
done

# ── 7. daemon-reload ─────────────────────────────────────────────────────────

log "Reloading systemd user daemon ..."
run systemctl --user daemon-reload
echo "  [ok]   daemon-reload"

# ── 8. Seed BotStore from config.toml (idempotent) ─────────────────────────
# Required since #1416: Authenticator reads from BotStore, not config.toml.
# Skipping this causes a hub crash-loop on first boot.
log "Seeding BotStore from config.toml ..."
run podman run --rm \
    -v "${HOME}/.roxabi/factory:/home/factory/.roxabi/factory:z" \
    -v "${HOME}/.roxabi/factory/config.toml:/app/config.toml:ro,z" \
    ghcr.io/roxabi/factory:staging \
    factory bot init

echo "  [ok]   BotStore seeded"

# ── 9. Install sync timer + service (idempotent) ───────────────────────────

log "Installing factory-quadlet-sync timer + service ..."
run make quadlet-sync-install

# ── 10. Enable host podman-auto-update timer ────────────────────────────────

log "Enabling podman-auto-update.timer (5-min cadence) ..."
run systemctl --user enable --now podman-auto-update.timer
echo "  [ok]   podman-auto-update.timer enabled"

log "Done. Services NOT restarted — run: systemctl --user start factory-nats factory-hub factory-telegram factory-discord factory-clipool factory-gh-helper factory-turn-writer factory-blobstore"
