#!/usr/bin/env bash
# Bootstrap Langfuse + OTel collector env files on the operator host (M₁).
# Idempotent: skips generation when langfuse.env already exists.
set -euo pipefail

ENV_DIR="${HOME}/.roxabi/factory/env"
STATE_DIR="${HOME}/.local/state/factory/langfuse"
LANGFUSE_ENV="${ENV_DIR}/langfuse.env"
OTEL_ENV="${ENV_DIR}/otel-collector.env"
REDIS_CONF="${STATE_DIR}/redis/redis.conf"

rand_hex() {
  openssl rand -hex "${1}"
}

rand_b64() {
  openssl rand -base64 "${1}" | tr -d '/+=' | head -c "${1}"
}

mkdir -p "${ENV_DIR}" \
  "${STATE_DIR}/postgres" \
  "${STATE_DIR}/clickhouse" \
  "${STATE_DIR}/clickhouse-logs" \
  "${STATE_DIR}/redis-data" \
  "${STATE_DIR}/minio/langfuse" \
  "${STATE_DIR}/redis"

if [[ -f "${LANGFUSE_ENV}" ]]; then
  echo "langfuse.env exists — skipping secret generation (${LANGFUSE_ENV})"
else
  POSTGRES_PASSWORD="$(rand_hex 16)"
  CLICKHOUSE_PASSWORD="$(rand_hex 16)"
  REDIS_AUTH="$(rand_hex 16)"
  MINIO_PASSWORD="$(rand_hex 16)"
  SALT="$(rand_hex 16)"
  ENCRYPTION_KEY="$(rand_hex 32)"
  NEXTAUTH_SECRET="$(rand_hex 32)"
  ADMIN_PASSWORD="$(rand_b64 24)"
  PUBLIC_KEY="pk-lf-$(rand_hex 12)"
  SECRET_KEY="sk-lf-$(rand_hex 24)"

  cat >"${REDIS_CONF}" <<EOF
requirepass ${REDIS_AUTH}
maxmemory-policy noeviction
EOF
  # 644: redis container runs non-root and must read the bind-mounted config.
  chmod 644 "${REDIS_CONF}"

  cat >"${LANGFUSE_ENV}" <<EOF
# Generated by deploy/scripts/bootstrap-langfuse.sh — do not commit.
NEXTAUTH_URL=http://127.0.0.1:3000
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@factory-langfuse-postgres:5432/postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
SALT=${SALT}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
TELEMETRY_ENABLED=false
CLICKHOUSE_MIGRATION_URL=clickhouse://factory-langfuse-clickhouse:9000
CLICKHOUSE_URL=http://factory-langfuse-clickhouse:8123
CLICKHOUSE_USER=clickhouse
CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
CLICKHOUSE_CLUSTER_ENABLED=false
REDIS_HOST=factory-langfuse-redis
REDIS_PORT=6379
REDIS_AUTH=${REDIS_AUTH}
REDISCLI_AUTH=${REDIS_AUTH}
MINIO_ROOT_USER=minio
MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
LANGFUSE_S3_EVENT_UPLOAD_BUCKET=langfuse
LANGFUSE_S3_EVENT_UPLOAD_REGION=auto
LANGFUSE_S3_EVENT_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_EVENT_UPLOAD_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
LANGFUSE_S3_EVENT_UPLOAD_ENDPOINT=http://factory-langfuse-minio:9000
LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true
LANGFUSE_S3_EVENT_UPLOAD_PREFIX=events/
LANGFUSE_S3_MEDIA_UPLOAD_BUCKET=langfuse
LANGFUSE_S3_MEDIA_UPLOAD_REGION=auto
LANGFUSE_S3_MEDIA_UPLOAD_ACCESS_KEY_ID=minio
LANGFUSE_S3_MEDIA_UPLOAD_SECRET_ACCESS_KEY=${MINIO_PASSWORD}
LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=http://factory-langfuse-minio:9000
LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=true
LANGFUSE_S3_MEDIA_UPLOAD_PREFIX=media/
LANGFUSE_INIT_ORG_ID=factory
LANGFUSE_INIT_ORG_NAME=Factory
LANGFUSE_INIT_PROJECT_ID=factory-traces
LANGFUSE_INIT_PROJECT_NAME=Factory-Traces
LANGFUSE_INIT_PROJECT_PUBLIC_KEY=${PUBLIC_KEY}
LANGFUSE_INIT_PROJECT_SECRET_KEY=${SECRET_KEY}
LANGFUSE_INIT_USER_EMAIL=admin@factory.local
LANGFUSE_INIT_USER_NAME=Factory-Admin
LANGFUSE_INIT_USER_PASSWORD=${ADMIN_PASSWORD}
EOF
  chmod 600 "${LANGFUSE_ENV}"
  echo "Wrote ${LANGFUSE_ENV}"
  echo "Langfuse admin: admin@factory.local / ${ADMIN_PASSWORD}"
  echo "API keys: ${PUBLIC_KEY} / ${SECRET_KEY}"
fi

# otel-collector.env — always (re)derive auth from langfuse.env keys.
PUBLIC_KEY="$(grep '^LANGFUSE_INIT_PROJECT_PUBLIC_KEY=' "${LANGFUSE_ENV}" | cut -d= -f2-)"
SECRET_KEY="$(grep '^LANGFUSE_INIT_PROJECT_SECRET_KEY=' "${LANGFUSE_ENV}" | cut -d= -f2-)"
AUTH_B64="$(printf '%s:%s' "${PUBLIC_KEY}" "${SECRET_KEY}" | base64 -w 0)"
cat >"${OTEL_ENV}" <<EOF
# Generated by deploy/scripts/bootstrap-langfuse.sh — do not commit.
LANGFUSE_OTEL_AUTH=${AUTH_B64}
EOF
chmod 600 "${OTEL_ENV}"
echo "Wrote ${OTEL_ENV}"