/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/roxabi.theme.ts
 * Command: astryx theme build src/astryx-theme/roxabi.theme.ts --out src/astryx-theme/built/roxabi.theme.css
 * Generated: 2026-07-01T13:39:10.639Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const roxabiTheme: DefinedTheme;
