/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/roxabi.theme.ts
 * Command: astryx theme build src/astryx-theme/roxabi.theme.ts --out src/astryx-theme/built/roxabi.theme.css
 * Generated: 2026-07-01T15:22:34.419Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const roxabiTheme: DefinedTheme;
