/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/astryx-theme/roxabi.theme.ts
 * Command: astryx theme build src/astryx-theme/roxabi.theme.ts --out src/astryx-theme/built/roxabi.theme.css
 * Generated: 2026-07-01T15:22:34.421Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}

declare module '@astryxdesign/core/Badge' {
  interface XDSBadgeVariantMap {
    'gray': true;
  }
}
