"""Render and parse NATS auth.conf from ACL matrix — #1017 T09."""

from __future__ import annotations

import re

from scripts._acl_models import LoadedMatrix, ParsedAuthConf, ParsedUser
from scripts._effective import effective_grants

_HEADER = (
    "# NATS nkey authorization — generated by lyra-acl genkeys\n"
    "# Spec: artifacts/specs/706-per-role-nkeys-acls-spec.mdx\n"
    "# TODO(ADR-045): ACL for roxabi-nats SDK identities intentionally omitted\n"
    "#                until the SDK extraction lands — rerun this script then.\n"
    "# DO NOT edit manually — regenerate with:"
    ' sudo env "PATH=$PATH" lyra-acl genkeys --regenerate'
)

_RE_DENY = re.compile(r"(\w+)\s*:\s*\{\s*deny\s*:\s*\[([^\]]*)\]")
_RE_ALLOW = re.compile(r"(\w+)\s*:\s*\{\s*allow\s*:\s*\[([^\]]*)\]")
_RE_NKEY = re.compile(r'nkey\s*:\s*"([^"]+)"')
_RE_COMMENT_NAME = re.compile(r"#\s+(\S+)")
_RE_ALLOW_RESP = re.compile(r"allow_responses\s*:\s*(true|false)")
_RE_PERMS = re.compile(r"permissions\s*:\s*\{(.*)\}", re.DOTALL)
_RE_DP = re.compile(r"default_permissions\s*:\s*\{(.*?)\}", re.DOTALL)
_RE_USERS = re.compile(r"users\s*:\s*\[(.*)\]", re.DOTALL)


def _quoted_list(items: list[str]) -> str:
    return ",".join(f'"{s}"' for s in items)


def _emit_user(
    name: str,
    pubkey: str,
    pub_allow: list[str],
    sub_allow: list[str],
    allow_responses: bool,
) -> str:
    """Return one users[] block matching bash emit_user output."""
    ar = "true" if allow_responses else "false"
    return (
        f"    {{\n"
        f'      nkey: "{pubkey}"\n'
        f"      # {name}\n"
        f"      permissions: {{\n"
        f"        publish:   {{ allow: [{_quoted_list(pub_allow)}] }}\n"
        f"        subscribe: {{ allow: [{_quoted_list(sub_allow)}] }}\n"
        f"        allow_responses: {ar}\n"
        f"      }}\n"
        f"    }}"
    )


def render_auth_conf(matrix: LoadedMatrix, pubkeys: dict[str, str]) -> str:
    """Render NATS auth.conf from matrix + pubkeys (active identities only)."""
    identities = matrix["identities"]
    grants = effective_grants(matrix)

    lines = [_HEADER, "authorization {", "  default_permissions: {"]
    lines.append('    publish:   { deny: [">"] }')
    lines.append('    subscribe: { deny: [">"] }')
    lines.append("  }")
    lines.append("  users: [")

    for name, identity in identities.items():
        if name not in grants:
            continue
        ar = identity.get("allow_responses", True)
        pub_allow, sub_allow = grants[name]
        block = _emit_user(name, pubkeys[name], pub_allow, sub_allow, ar)
        lines.append(block)

    lines.append("  ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def _deny_list(block: str, keyword: str) -> tuple[str, ...]:
    for m in _RE_DENY.finditer(block):
        if m.group(1) == keyword:
            return tuple(
                s.strip().strip('"') for s in m.group(2).split(",") if s.strip()
            )
    return ()


def _allow_set(block: str, keyword: str) -> frozenset[str]:
    for m in _RE_ALLOW.finditer(block):
        if m.group(1) == keyword:
            return frozenset(
                s.strip().strip('"') for s in m.group(2).split(",") if s.strip()
            )
    return frozenset()


def _split_user_blocks(users_block: str) -> list[str]:
    """Brace-depth scanner: split top-level {} blocks."""
    blocks: list[str] = []
    depth, start = 0, -1
    for i, ch in enumerate(users_block):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start != -1:
                blocks.append(users_block[start : i + 1])
                start = -1
    return blocks


def _parse_user_block(block: str) -> ParsedUser:
    nkey_m = _RE_NKEY.search(block)
    name_m = _RE_COMMENT_NAME.search(block)
    perm_m = _RE_PERMS.search(block)
    perm = perm_m.group(1) if perm_m else ""
    ar_m = _RE_ALLOW_RESP.search(perm)
    return ParsedUser(
        nkey=nkey_m.group(1) if nkey_m else "",
        publish_allow=_allow_set(perm, "publish"),
        subscribe_allow=_allow_set(perm, "subscribe"),
        allow_responses=ar_m.group(1) == "true" if ar_m else False,
        comment_name=name_m.group(1) if name_m else "",
    )


def parse_auth_conf(text: str) -> ParsedAuthConf:
    """Parse auth.conf text emitted by render_auth_conf or lyra-acl genkeys."""
    dp_m = _RE_DP.search(text)
    dp = dp_m.group(1) if dp_m else ""
    users_m = _RE_USERS.search(text)
    users_block = users_m.group(1) if users_m else ""
    return ParsedAuthConf(
        default_publish_deny=_deny_list(dp, "publish"),
        default_subscribe_deny=_deny_list(dp, "subscribe"),
        users=tuple(_parse_user_block(b) for b in _split_user_blocks(users_block)),
    )
