"""Render and parse NATS auth.conf from ACL matrix — #1017 T09."""

from __future__ import annotations

import re

from scripts._acl_models import LoadedMatrix, ParsedAuthConf, ParsedUser

_HEADER = """\
# NATS nkey authorization — generated by gen-nkeys.sh
# Spec: artifacts/specs/706-per-role-nkeys-acls-spec.mdx
# TODO(ADR-045): ACL for roxabi-nats SDK identities intentionally omitted
#                until the SDK extraction lands — rerun this script then.
# DO NOT edit manually — regenerate with: sudo ./deploy/nats/gen-nkeys.sh --regenerate"""


def _emit_user(
    name: str,
    pubkey: str,
    pub_allow: list[str],
    sub_allow: list[str],
    allow_responses: bool,
) -> str:
    """Return a single users[] block string matching bash emit_user output."""
    pub_items = ",".join(f'"{s}"' for s in pub_allow)
    sub_items = ",".join(f'"{s}"' for s in sub_allow)
    ar = "true" if allow_responses else "false"
    return (
        f'    {{\n'
        f'      nkey: "{pubkey}"\n'
        f'      # {name}\n'
        f'      permissions: {{\n'
        f'        publish:   {{ allow: [{pub_items}] }}\n'
        f'        subscribe: {{ allow: [{sub_items}] }}\n'
        f'        allow_responses: {ar}\n'
        f'      }}\n'
        f'    }}'
    )


def render_auth_conf(matrix: LoadedMatrix, pubkeys: dict[str, str]) -> str:
    """Render NATS auth.conf text from matrix + pubkeys (active identities only)."""
    identities = matrix["identities"]
    flows = matrix.get("request_reply_flows", [])

    # Build per-identity pub/sub allow lists (mutable copies)
    pub_allow: dict[str, list[str]] = {}
    sub_allow: dict[str, list[str]] = {}

    for name, identity in identities.items():
        if identity["status"] == "retired":
            continue
        pub_allow[name] = list(identity.get("publish", []))
        sub_allow[name] = list(identity.get("subscribe", []))

    # Derive inbox grants from request_reply_flows
    for flow in flows:
        requester = flow["requester"]
        responder = flow["responder"]
        inbox = f"_inbox.{requester}.>"

        # Add inbox to requester's subscribe (if not already present)
        if requester in sub_allow and inbox not in sub_allow[requester]:
            sub_allow[requester].append(inbox)

        # Add inbox to responder's publish (if not already present)
        if responder in pub_allow and inbox not in pub_allow[responder]:
            pub_allow[responder].append(inbox)

    lines = [_HEADER, "authorization {", "  default_permissions: {"]
    lines.append('    publish:   { deny: [">"] }')
    lines.append('    subscribe: { deny: [">"] }')
    lines.append("  }")
    lines.append("  users: [")

    for name in identities:
        if identities[name]["status"] == "retired":
            continue
        pubkey = pubkeys[name]
        ar = identities[name].get("allow_responses", True)
        block = _emit_user(name, pubkey, pub_allow[name], sub_allow[name], ar)
        lines.append(block)

    lines.append("  ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def parse_auth_conf(text: str) -> ParsedAuthConf:
    """Parse the auth.conf format emitted by render_auth_conf / gen-nkeys.sh.

    Only handles the exact subset that render_auth_conf emits.
    """
    # Extract default_permissions deny lists
    def _deny_list(section: str, keyword: str) -> tuple[str, ...]:
        m = re.search(
            rf'{keyword}\s*:\s*\{{\s*deny\s*:\s*\[([^\]]*)\]', section
        )
        if not m:
            return ()
        return tuple(s.strip().strip('"') for s in m.group(1).split(",") if s.strip())

    dp_match = re.search(
        r'default_permissions\s*:\s*\{(.*?)\}', text, re.DOTALL
    )
    dp_block = dp_match.group(1) if dp_match else ""
    default_pub_deny = _deny_list(dp_block, "publish")
    default_sub_deny = _deny_list(dp_block, "subscribe")

    # Extract users block
    users_match = re.search(r'users\s*:\s*\[(.*)\]', text, re.DOTALL)
    users_block = users_match.group(1) if users_match else ""

    # Split into individual user blocks: each starts with `{` and ends with `}`
    # Use a simple brace-depth scanner
    user_blocks: list[str] = []
    depth = 0
    start = -1
    for i, ch in enumerate(users_block):
        if ch == "{":
            if depth == 0:
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0 and start != -1:
                user_blocks.append(users_block[start : i + 1])
                start = -1

    parsed_users: list[ParsedUser] = []
    for block in user_blocks:
        # nkey
        nkey_m = re.search(r'nkey\s*:\s*"([^"]+)"', block)
        nkey = nkey_m.group(1) if nkey_m else ""

        # comment name (# <name>)
        name_m = re.search(r'#\s+(\S+)', block)
        comment_name = name_m.group(1) if name_m else ""

        # permissions block
        perm_m = re.search(r'permissions\s*:\s*\{(.*)\}', block, re.DOTALL)
        perm_block = perm_m.group(1) if perm_m else ""

        def _allow_set(b: str, keyword: str) -> frozenset[str]:
            m = re.search(rf'{keyword}\s*:\s*\{{\s*allow\s*:\s*\[([^\]]*)\]', b)
            if not m:
                return frozenset()
            raw = m.group(1)
            return frozenset(
                s.strip().strip('"') for s in raw.split(",") if s.strip()
            )

        pub = _allow_set(perm_block, "publish")
        sub = _allow_set(perm_block, "subscribe")

        ar_m = re.search(r'allow_responses\s*:\s*(true|false)', perm_block)
        ar = ar_m.group(1) == "true" if ar_m else False

        parsed_users.append(
            ParsedUser(
                nkey=nkey,
                publish_allow=pub,
                subscribe_allow=sub,
                allow_responses=ar,
                comment_name=comment_name,
            )
        )

    return ParsedAuthConf(
        default_publish_deny=default_pub_deny,
        default_subscribe_deny=default_sub_deny,
        users=tuple(parsed_users),
    )
