#!/usr/bin/env bash
# Quadlet template purity check — #1369
#
# Enforces 3 invariants on tracked deploy/quadlet/*.container.tmpl:
#   (i)   no `Secret=lyra-bot-*` lines (must come from render at install time)
#   (ii)  no `# --- BEGIN ... ---` / `# --- END ... ---` splice blocks
#   (iii) tools/render_quadlet.py exists (the render step the templates require)
#
# Run locally: `make quadlet-lint` (or directly: `bash tools/check_quadlet_template_purity.sh`)
# Run in CI:   .github/workflows/quadlet-lint.yml

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

FAIL=0
TMPL_GLOB="deploy/quadlet/*.container.tmpl"

# ── Invariant (i): no Secret=lyra-bot- lines in tracked templates ─────────────
# These must come from tools/render_quadlet.py at install time (A5(i)).
# Anchored at line start to avoid matching documentation comments.
MATCHES_I=$(grep -rn "^Secret=lyra-bot-" $TMPL_GLOB 2>/dev/null || true)
if [ -n "$MATCHES_I" ]; then
    echo "FAIL (i): 'Secret=lyra-bot-' found in tracked .tmpl — must be rendered at install time, not tracked." >&2
    echo "  These lines must be generated by tools/render_quadlet.py; remove them from the template." >&2
    printf '%s\n' "$MATCHES_I" | sed 's/^/  /' >&2
    FAIL=1
fi

# ── Invariant (ii): no BEGIN/END splice blocks in tracked templates ───────────
# The operator-local splicing pattern is forbidden in tracked files (A5(ii)).
# Even placeholder/empty blocks are rejected — the pattern itself is the anti-pattern.
MATCHES_II=$(grep -rn "^# --- BEGIN .* ---" $TMPL_GLOB 2>/dev/null || true)
if [ -n "$MATCHES_II" ]; then
    echo "FAIL (ii): '# --- BEGIN ... ---' splice block found in tracked .tmpl — operator-local splicing is forbidden in tracked templates." >&2
    echo "  Use a {{marker}} placeholder instead; splice content is injected at render time." >&2
    printf '%s\n' "$MATCHES_II" | sed 's/^/  /' >&2
    FAIL=1
fi

# ── Invariant (iii): tools/render_quadlet.py must exist ──────────────────────
# Without the render script, `make quadlet-install` would copy stub templates
# with {{bot_secrets}} markers verbatim, producing broken Quadlets (A5(iii)).
if [ ! -f tools/render_quadlet.py ]; then
    echo "FAIL (iii): tools/render_quadlet.py is missing — the render script is required." >&2
    echo "  Without it, 'make quadlet-install' would copy {{bot_secrets}} markers verbatim into Quadlet units." >&2
    FAIL=1
fi

exit $FAIL
