#!/usr/bin/env bash
# Quadlet template purity check — #1369
#
# Three checks (two are content-purity on .tmpl files, one is a presence guard
# on the render script):
#   (i)   no `Secret=lyra-bot-*` lines in any tracked .tmpl (content) —
#         the pattern is banned everywhere, including comments, as a commented
#         Secret=lyra-bot- shape is itself evidence of manual-splice thinking
#   (ii)  no `# --- BEGIN ... ---` splice blocks in any tracked .tmpl (content)
#   (iii) tools/render_quadlet.py present (sibling-file presence guard)
#
# Run locally: `make quadlet-lint` (or directly: `bash tools/check_quadlet_template_purity.sh`)
# Run in CI:   .github/workflows/quadlet-lint.yml

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

fail=0

# ── Invariant (i): no Secret=lyra-bot- lines in tracked templates ─────────────
# These must come from tools/render_quadlet.py at install time (A5(i)).
# Pattern is banned everywhere in tracked .tmpl, including comments.
violations=$(find deploy/quadlet -maxdepth 1 -name '*.container.tmpl' -print0 \
    | xargs -0 grep -nE 'Secret=lyra-bot-' 2>/dev/null || true)
if [ -n "$violations" ]; then
    echo "FAIL (i): 'Secret=lyra-bot-' found in tracked .tmpl — must be rendered at install time, not tracked." >&2
    echo "  These lines must be generated by tools/render_quadlet.py; remove them from the template." >&2
    printf '%s\n' "$violations" | sed 's/^/  /' >&2
    fail=1
fi

# ── Invariant (ii): no BEGIN/END splice blocks in tracked templates ───────────
# The operator-local splicing pattern is forbidden in tracked files (A5(ii)).
# Even placeholder/empty blocks are rejected — the pattern itself is the anti-pattern.
violations=$(find deploy/quadlet -maxdepth 1 -name '*.container.tmpl' -print0 \
    | xargs -0 grep -nE '^# --- BEGIN .* ---' 2>/dev/null || true)
if [ -n "$violations" ]; then
    echo "FAIL (ii): '# --- BEGIN ... ---' splice block found in tracked .tmpl — operator-local splicing is forbidden in tracked templates." >&2
    echo "  Use a {{marker}} placeholder instead; splice content is injected at render time." >&2
    printf '%s\n' "$violations" | sed 's/^/  /' >&2
    fail=1
fi

# ── Invariant (iii): tools/render_quadlet.py must exist ──────────────────────
# Without the render script, `make quadlet-install` would copy stub templates
# with {{bot_secrets}} markers verbatim, producing broken Quadlets (A5(iii)).
if [ ! -f tools/render_quadlet.py ]; then
    echo "FAIL (iii): tools/render_quadlet.py is missing — the render script is required." >&2
    echo "  Without it, 'make quadlet-install' would copy {{bot_secrets}} markers verbatim into Quadlet units." >&2
    fail=1
fi

exit $fail
