#!/usr/bin/env python3
"""emit_secrets_manifest.py — generate deploy/generated/secrets-manifest.sh

Reads:
  - deploy/quadlet.toml        required_secrets per [component.<name>]
  - deploy/secrets-policy.toml name → policy + source

Emits:
  - deploy/generated/secrets-manifest.sh  bash declare -A SECRET_SOURCES + SECRET_POLICY

Contracts (from spec §Risks):
  - secret name = Secret= value.split(",")[0]  (strip Podman options)
  - {{bot_secrets}} template placeholder        EXCLUDED (not a real secret name)
  - stdlib only (tomllib)                       no third-party deps
"""

import pathlib
import sys
import tomllib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
QUADLET_TOML = REPO_ROOT / "deploy" / "quadlet.toml"
POLICY_TOML = REPO_ROOT / "deploy" / "secrets-policy.toml"
QUADLET_DIR = REPO_ROOT / "deploy" / "quadlet"
OUTPUT = REPO_ROOT / "deploy" / "generated" / "secrets-manifest.sh"

# Template placeholder that render_quadlet.py injects per-bot secrets into.
# Never a real Podman secret name — must be excluded from the manifest.
BOT_SECRETS_PLACEHOLDER = "{{bot_secrets}}"


def parse_unit_secret_names(unit_path: pathlib.Path) -> list[str]:
    """Extract secret names from Secret= lines in a .container or .container.tmpl file.

    Contract: name = value.split(",")[0] (strip type=, target=, uid=, … options).
    Excludes the {{bot_secrets}} template placeholder.
    """
    names: list[str] = []
    for line in unit_path.read_text().splitlines():
        stripped = line.strip()
        if not stripped.startswith("Secret="):
            continue
        value = stripped[len("Secret=") :]
        if BOT_SECRETS_PLACEHOLDER in value:
            continue
        name = value.split(",")[0].strip()
        if name:
            names.append(name)
    return names


def list_unit_secrets_cli(unit_path: pathlib.Path) -> int:
    """CLI mode: print one secret name per line for a given unit file and exit."""
    if not unit_path.exists():
        print(f"ERROR: unit file not found: {unit_path}", file=sys.stderr)
        return 2
    for name in parse_unit_secret_names(unit_path):
        print(name)
    return 0


def main() -> int:
    # CLI mode: --list-unit-secrets <unit_file>
    if len(sys.argv) >= 3 and sys.argv[1] == "--list-unit-secrets":
        return list_unit_secrets_cli(pathlib.Path(sys.argv[2]))
    if len(sys.argv) == 2 and sys.argv[1] in ("-h", "--help"):
        print(
            "Usage:\n"
            "  emit_secrets_manifest.py"
            "                         -- generate manifest\n"
            "  emit_secrets_manifest.py --list-unit-secrets <f>"
            " -- list secret names in unit file"
        )
        return 0

    with QUADLET_TOML.open("rb") as f:
        quadlet = tomllib.load(f)
    with POLICY_TOML.open("rb") as f:
        policy = tomllib.load(f)

    components: dict[str, dict] = quadlet.get("component", {})
    policies: dict[str, dict] = policy.get("secret", {})

    # Collect ALL unique secret names from required_secrets across all components.
    all_secrets: set[str] = set()
    for comp_data in components.values():
        for sname in comp_data.get("required_secrets", []):
            all_secrets.add(sname)

    # Build output arrays — source and policy for every declared secret.
    source_entries: list[str] = []
    policy_entries: list[str] = []
    errors: list[str] = []

    for sname in sorted(all_secrets):
        if sname not in policies:
            errors.append(
                f"  {sname!r}: in required_secrets but not in secrets-policy.toml"
            )
            continue
        p = policies[sname]
        src = p.get("source")
        pol = p.get("policy")
        if src is None or pol is None:
            errors.append(
                f"  {sname!r}: malformed entry in secrets-policy.toml"
                f" (missing {'source' if src is None else 'policy'} key)"
            )
            continue
        source_entries.append(f'    [{sname}]="{src}"')
        policy_entries.append(f'    [{sname}]="{pol}"')

    if errors:
        print(
            "ERROR: secrets missing from deploy/secrets-policy.toml:", file=sys.stderr
        )
        for e in errors:
            print(e, file=sys.stderr)
        return 1

    # Produce the manifest.
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "# GENERATED by tools/emit_secrets_manifest.py — do not edit",
        "# Source: deploy/quadlet.toml (required_secrets) + deploy/secrets-policy.toml",
        "# Regenerate: python3 tools/emit_secrets_manifest.py",
        "",
        "# SECRET_SOURCES maps secret name → host file path",
        "# (relative to the factory data dir, e.g. ~/.roxabi/factory/)",
        "# Value 'n/a' = no file-based source (generated or externally provisioned).",
        "declare -A SECRET_SOURCES=(",
        *source_entries,
        ")",
        "",
        "# SECRET_POLICY maps secret name → policy",
        "# Values: nats-seed | nats-auth | generated | optional",
        "declare -A SECRET_POLICY=(",
        *policy_entries,
        ")",
    ]
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"Written {OUTPUT.relative_to(REPO_ROOT)} ({len(all_secrets)} secrets)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
