#!/usr/bin/env python3
"""emit_secrets_manifest.py — generate deploy/generated/secrets-manifest.sh

Reads:
  - deploy/quadlet.toml        required_secrets per [component.<name>]
  - deploy/secrets-policy.toml name → policy + source

Emits:
  - deploy/generated/secrets-manifest.sh  bash declare -A SECRET_SOURCES + SECRET_POLICY

Contracts (from spec §Risks):
  - secret name = Secret= value.split(",")[0]  (strip Podman options)
  - {{bot_secrets}} template placeholder        EXCLUDED (not a real secret name)
  - stdlib only (tomllib)                       no third-party deps
"""

import pathlib
import sys
import tomllib

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
QUADLET_TOML = REPO_ROOT / "deploy" / "quadlet.toml"
POLICY_TOML = REPO_ROOT / "deploy" / "secrets-policy.toml"
QUADLET_DIR = REPO_ROOT / "deploy" / "quadlet"
OUTPUT = REPO_ROOT / "deploy" / "generated" / "secrets-manifest.sh"

# Template placeholder that render_quadlet.py injects per-bot secrets into.
# Never a real Podman secret name — must be excluded from the manifest.
BOT_SECRETS_PLACEHOLDER = "{{bot_secrets}}"


def parse_unit_secret_names(unit_path: pathlib.Path) -> list[str]:
    """Extract secret names from Secret= lines in a .container or .container.tmpl file.

    Contract: name = value.split(",")[0] (strip type=, target=, uid=, … options).
    Excludes the {{bot_secrets}} template placeholder.
    """
    names: list[str] = []
    for line in unit_path.read_text().splitlines():
        stripped = line.strip()
        if not stripped.startswith("Secret="):
            continue
        value = stripped[len("Secret=") :]
        if BOT_SECRETS_PLACEHOLDER in value:
            continue
        name = value.split(",")[0].strip()
        if name:
            names.append(name)
    return names


def collect_unit_secrets_index() -> dict[str, list[str]]:
    """Return {component_name: [secret_name, ...]} from the actual unit files."""
    index: dict[str, list[str]] = {}
    for unit_file in QUADLET_DIR.iterdir():
        if not (
            unit_file.suffix in (".container", ".tmpl")
            or unit_file.name.endswith(".container.tmpl")
        ):
            continue
        # Derive component name: factory-<component>.container(.tmpl) → <component>
        stem = unit_file.name
        for suffix in (".container.tmpl", ".container"):
            if stem.endswith(suffix):
                stem = stem[: -len(suffix)]
                break
        if stem.startswith("factory-"):
            component = stem[len("factory-") :]
        else:
            component = stem
        secrets = parse_unit_secret_names(unit_file)
        if secrets:
            index[component] = secrets
    return index


def main() -> int:
    with QUADLET_TOML.open("rb") as f:
        quadlet = tomllib.load(f)
    with POLICY_TOML.open("rb") as f:
        policy = tomllib.load(f)

    components: dict[str, dict] = quadlet.get("component", {})
    policies: dict[str, dict] = policy.get("secret", {})

    # Collect ALL unique secret names from required_secrets across all components.
    all_secrets: set[str] = set()
    for comp_data in components.values():
        for sname in comp_data.get("required_secrets", []):
            all_secrets.add(sname)

    # Build output arrays — source and policy for every declared secret.
    source_entries: list[str] = []
    policy_entries: list[str] = []
    errors: list[str] = []

    for sname in sorted(all_secrets):
        if sname not in policies:
            errors.append(
                f"  {sname!r}: in required_secrets but not in secrets-policy.toml"
            )
            continue
        p = policies[sname]
        source_entries.append(f'    [{sname}]="{p["source"]}"')
        policy_entries.append(f'    [{sname}]="{p["policy"]}"')

    if errors:
        print(
            "ERROR: secrets missing from deploy/secrets-policy.toml:", file=sys.stderr
        )
        for e in errors:
            print(e, file=sys.stderr)
        return 1

    # Produce the manifest.
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "# GENERATED by tools/emit_secrets_manifest.py — do not edit",
        "# Source: deploy/quadlet.toml (required_secrets) + deploy/secrets-policy.toml",
        "# Regenerate: python3 tools/emit_secrets_manifest.py",
        "",
        "# SECRET_SOURCES maps secret name → host file path",
        "# (relative to the factory data dir, e.g. ~/.roxabi/factory/)",
        "# Value 'n/a' = no file-based source (generated or externally provisioned).",
        "declare -A SECRET_SOURCES=(",
        *source_entries,
        ")",
        "",
        "# SECRET_POLICY maps secret name → policy",
        "# Values: nats-seed | nats-auth | generated | optional",
        "declare -A SECRET_POLICY=(",
        *policy_entries,
        ")",
    ]
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"Written {OUTPUT.relative_to(REPO_ROOT)} ({len(all_secrets)} secrets)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
