"""Tier-1 generated architecture snapshot generator."""

import configparser
import json
import sys
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib

_HEADER = (
    "<!-- AUTOGENERATED — DO NOT EDIT BY HAND. "
    "Regenerated by tools/generate_architecture_snapshot.py -->"
)
_FOOTER = (
    "*Generated by tools/generate_architecture_snapshot.py "
    "— DO NOT EDIT BY HAND*"
)


def _parse_list(value: str) -> list[str]:
    """Parse a comma-separated list from importlinter."""
    if not value or not value.strip():
        return []
    return [v.strip() for v in value.split("\n") if v.strip()]


def parse_importlinter(root: Path) -> list[dict]:
    path = root / ".importlinter"
    if not path.exists():
        print(f"ERROR: missing {path}", file=sys.stderr)
        sys.exit(2)
    config = configparser.ConfigParser()
    config.read(path)
    contracts = []
    for section in config.sections():
        if section.startswith("importlinter:contract:"):
            contracts.append(
                {
                    "name": config.get(section, "name", fallback=""),
                    "type": config.get(section, "type", fallback=""),
                    "layers": _parse_list(config.get(section, "layers", fallback="")),
                    "source_modules": _parse_list(
                        config.get(section, "source_modules", fallback="")
                    ),
                    "forbidden_modules": _parse_list(
                        config.get(section, "forbidden_modules", fallback="")
                    ),
                    "ignore_imports": _parse_list(
                        config.get(section, "ignore_imports", fallback="")
                    ),
                    "allow_indirect_imports": config.getboolean(
                        section, "allow_indirect_imports", fallback=False
                    ),
                }
            )
    return sorted(contracts, key=lambda c: c["name"])


def parse_quadlet(root: Path) -> dict:
    path = root / "deploy" / "quadlet.toml"
    if not path.exists():
        print(f"ERROR: missing {path}", file=sys.stderr)
        sys.exit(2)
    with open(path, "rb") as f:
        return tomllib.load(f)


def parse_acl_matrix(root: Path) -> dict:
    path = root / "deploy" / "nats" / "acl-matrix.json"
    if not path.exists():
        print(f"ERROR: missing {path}", file=sys.stderr)
        sys.exit(2)
    with open(path) as f:
        return json.load(f)


def _render_contracts(contracts: list[dict]) -> list[str]:
    lines: list[str] = []
    for c in contracts:
        lines.append(f"\n### {c['name']}\n")
        lines.append(f"- **Type:** {c['type']}")
        if c.get("layers"):
            lines.append(f"- **Layers:** {', '.join(c['layers'])}")
        if c.get("source_modules"):
            lines.append(f"- **Source modules:** {', '.join(c['source_modules'])}")
        if c.get("forbidden_modules"):
            lines.append(
                f"- **Forbidden modules:** {', '.join(c['forbidden_modules'])}"
            )
        if c.get("ignore_imports"):
            lines.append(f"- **Ignore imports:** {', '.join(c['ignore_imports'])}")
        lines.append(
            f"- **Allow indirect imports:** {c.get('allow_indirect_imports', False)}"
        )
    return lines


def _render_nats(acl: dict) -> list[str]:
    lines: list[str] = []
    subjects = sorted(acl.get("subjects", []))
    for sub in subjects:
        lines.append(f"- `{sub}`")

    identities = acl.get("identities", {})
    for name in sorted(identities.keys()):
        ident = identities[name]
        lines.append(f"\n### {name}")
        if ident.get("publish"):
            lines.append(f"- **Publish:** {', '.join(sorted(ident['publish']))}")
        if ident.get("subscribe"):
            lines.append(f"- **Subscribe:** {', '.join(sorted(ident['subscribe']))}")
    return lines


def _render_topology(topology: dict) -> list[str]:
    lines: list[str] = []
    components = topology.get("component", {})
    for name in sorted(components.keys()):
        comp = components[name]
        lines.append(f"\n### {name}")
        lines.append(f"- **Container:** {comp.get('container', 'N/A')}")
        if comp.get("required_secrets"):
            lines.append(
                f"- **Required secrets:** {', '.join(sorted(comp['required_secrets']))}"
            )
        if comp.get("host_roles"):
            lines.append(f"- **Host roles:** {', '.join(sorted(comp['host_roles']))}")
    return lines


def render_markdown(contracts: list[dict], topology: dict, acl: dict) -> str:
    lines = [
        _HEADER,
        "",
        "# Architecture Snapshot",
        "",
        "## Layer Map",
        "",
    ]
    lines.extend(_render_contracts(contracts))
    lines.extend(["", "## NATS Subjects & Identities", ""])
    lines.extend(_render_nats(acl))
    lines.extend(["", "## Process Topology", ""])
    lines.extend(_render_topology(topology))
    lines.extend(["", "---", _FOOTER])
    return "\n".join(lines) + "\n"


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Generate architecture snapshot")
    parser.add_argument("root", type=Path, default=Path("."), nargs="?")
    args = parser.parse_args()

    root = args.root.resolve()
    contracts = parse_importlinter(root)
    topology = parse_quadlet(root)
    acl = parse_acl_matrix(root)

    output = root / "docs" / "architecture" / "CURRENT.generated.md"
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render_markdown(contracts, topology, acl), encoding="utf-8")
    print(f"Generated {output}")


if __name__ == "__main__":
    main()
