#!/usr/bin/env bash
# Install the repo git hooks (pre-commit + pre-push → scripts/qg via the
# pre-commit framework) into the EFFECTIVE hooks directory.
#
# Why not `pre-commit install`: it refuses to run whenever core.hooksPath is
# set at ANY scope ("Cowardly refusing…"), and this machine sets it both
# globally (ccc reindex hooks) and repo-locally — which is how the repo ended
# up with a .pre-commit-config.yaml but zero installed hooks, i.e. nothing ran
# at commit/push time. This script writes the same `pre-commit hook-impl`
# dispatcher wrappers `pre-commit install` would have written, directly into
# the effective hooks dir, and re-chains any global hooks (ccc post-merge /
# post-rewrite) that a repo-local core.hooksPath override shadows.
#
# Idempotent — safe to re-run; invoked by tools/dev-setup.sh and
# tools/worktree-setup.sh (hooks live in the shared common hooks dir, so one
# install covers the main checkout and every linked worktree).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

if ! command -v pre-commit >/dev/null 2>&1; then
  echo "install-hooks: pre-commit not found — install it (e.g. 'uv tool install pre-commit') and re-run" >&2
  exit 2
fi

hooks_dir="$(git config core.hooksPath || true)"
if [[ -z "$hooks_dir" ]]; then
  hooks_dir="$(git rev-parse --path-format=absolute --git-common-dir)/hooks"
fi
mkdir -p "$hooks_dir"

write_dispatcher() {
  local hook_type="$1"
  cat >"${hooks_dir}/${hook_type}" <<EOF
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh — do not edit; re-run the script instead.
if ! command -v pre-commit >/dev/null 2>&1; then
  echo "pre-commit not found — refusing to skip quality gates silently." >&2
  echo "Fix: uv tool install pre-commit  (or bypass once with --no-verify)" >&2
  exit 1
fi
exec pre-commit hook-impl --config=.pre-commit-config.yaml --hook-type=${hook_type} --hook-dir "${hooks_dir}" -- "\$@"
EOF
  chmod +x "${hooks_dir}/${hook_type}"
  echo "install-hooks: wrote ${hooks_dir}/${hook_type}"
}

write_dispatcher pre-commit
write_dispatcher pre-push

# A repo-local core.hooksPath shadows the global hooks dir entirely — re-chain
# any executable global hooks (post-merge/post-rewrite ccc reindex) so setting
# a local hooksPath doesn't silently disable them.
global_dir="$(git config --global core.hooksPath || true)"
if [[ -n "$global_dir" && "$global_dir" != "$hooks_dir" ]]; then
  for hook_type in post-merge post-rewrite; do
    if [[ -x "${global_dir}/${hook_type}" ]]; then
      cat >"${hooks_dir}/${hook_type}" <<EOF
#!/usr/bin/env bash
# Generated by tools/install-hooks.sh — chains the global ${hook_type} hook
# that the repo-local core.hooksPath override would otherwise shadow.
exec "${global_dir}/${hook_type}" "\$@"
EOF
      chmod +x "${hooks_dir}/${hook_type}"
      echo "install-hooks: chained global ${hook_type} → ${global_dir}/${hook_type}"
    fi
  done
fi

echo "install-hooks: done (hooks dir: ${hooks_dir})"
